config/routes.rb
Rails.application.routes.draw do

  match '/signup', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/authenticate',  to: 'sessions#create', via: 'post'

  resources :users do
    resources :tasks  end

  resources :password_resets

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :title, presence: true,
    length: {maximum: 68}
  validates :priority,
    numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }


  scope :complete, -> { where(complete: true) }
  scope :incomplete, -> { where(complete: false) }


  def self.maximum_priority
    Task.maximum(:priority) || 0
  end

  def set_maximum_priority
    self.priority = self.class.maximum_priority + 1

    self
  end

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :first_name, presence: true,
            length: {maximum: 20}
  validates :last_name,  presence: true,
            length: {maximum: 40}
  validates :email, presence: true,
            format: {with: EMAIL_REGEX},
            uniqueness:  {case_sensitive: true}
  validates :password,
            length: {within: 6..40}, on: :create

  def full_name
    name = [first_name, last_name].join(' ').strip
    name.blank? ? email : name
  end

  def send_password_reset
    UserMailer.password_reset(self).deliver_now
  end

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


 private


    def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    helper_method :current_user

    def authorize
      redirect_to login_url, alert: "Not authorized" if current_user.nil?
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user
     user.send_password_reset
     redirect_to login_url, notice: "Email sent with password reset instructions"
    else
     redirect_to login_url, notice: "The user does not exist"
   end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find_by_email(params[:id])
    if @user.update(user_params)
      redirect_to root_url, notice: "Password has been reset"
    else
      render 'edit'
    end
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_tasks_path(current_user)
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to signup_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authorize, only: [:edit, :new, :destroy, :index]
  helper_method :sort_column, :sort_direction

  def index
    @tasks = current_user.tasks.order(sort_column + " " + sort_direction)
    @task = Task.new
  end

  def show
  end

  def edit
    @task = Task.find(params[:id])
  end

  def new
  end

  def create
    @task = current_user.tasks.build(task_params).set_maximum_priority
    @task.complete = false


    respond_to do |format|
      if @task.save
        format.js
      else
        format.js
      end
    end
  end

  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update(task_params)
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { head :no_content }
      end
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_to {|format| format.js }
  end

  private

  def task_params
    params.require(:task).permit(:id, :title, :due_date, :priority, :complete)
  end

  def sort_column
    params[:sort] || "id"
  end

  def sort_direction
    params[:direction] || "asc"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authorize, only: [:edit, :destroy, :index]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      UserMailer.signup_confirmation(@user).deliver_now
      redirect_to user_tasks_path(current_user.id), notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to {|format| format.js }
  end

  private


  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == params[:sort] && params[:direction] == 'asc' ? 'desc' : 'asc'
  link_to title, :sort => column, :direction => direction, remote: true
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Greenbull</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <div id = "content">

  <% flash.each do |message_type, message| %>
    <div class="alert">
      <div class="flash-<%= message_type %>"><%= message %></div>
    </div>
  <% end %>


    <div id="user_header">
      <% if current_user %>
        <b><%= current_user.full_name %></b> |
        <%= link_to "Log Out", logout_path("current"), method: 'delete' %><br />
      <% else %>
        <div class="links">
           <%= link_to "Sign Up", signup_path %>
         <br>
           <%= link_to "Log In", login_path %>
         <br>
           <%= link_to "Forgot your password?", new_password_reset_path %>
        </div>
      <% end %>
    </div>

<%= yield %>

 </div>

</body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_for @user, url: password_reset_path(params[:id]) do |f| %>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

  <p>
    <div><%= f.label :password %></div>
    <%= f.password_field :password %>
  </p>

  <p>
    <div><%= f.label :password_confirmation %></div>
    <%= f.password_field :password_confirmation %>
  </p>

  <div class="button">
    <%= f.submit "Update password", class: "btn btn-default" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<%= form_tag password_resets_path do %>

  <div><%= label_tag :email %></div>

  <%= text_field_tag :email, params[:email] %>

  <div class="button">
    <%= submit_tag "Reset Password", class: "btn btn-default" %>
  </div>

<% end %>

app/views/tasks/_form.html.erb
<%= form_for [current_user, @task], remote: true  do |f| %>
  <%= f.text_field :title %>
  <%= f.hidden_field :user_id, value: params[:user_id] %>
  <%= f.submit  class: "btn btn-default" %>
<% end %>

app/views/tasks/_task.html.erb
<div class='tasks'>
  <div class='hovering' id="task_<%= task.id %>">

    <span class="trash-icon">
      <%= link_to user_task_path(current_user, task.id), method: :delete,
        data: { confirm: 'Are you sure?' }, remote: true do %>
        <i class="glyphicon glyphicon-trash"></i>
      <% end %>
    </span>

     <span class ="checkbox">
       <input type="checkbox" class='check' onclick="pressing(this);" data-id="<%= task.id %>" data-user-id="<%= current_user.id %>" data-complete="<%= task.complete %>" >
     </span>

    <span class="title">
      <a href="#" data-xeditable="true" data-showButtons='false' data-pk="task" id='task' data-model='task' data-name='title' data-url="/users/<%= current_user.id %>/tasks/<%= task.id %>" data-title="Enter title">
      <%= task.title %>
      </a>
    </span>

    <br>

    <i>due date:</i>

    <a href="#" data-type='date' data-showButtons='false' data-mode="popup" data-placement="bottom" data-format ='yyyy-mm-dd' placement='right' data-xeditable='true' data-pk='task' data-model='task' data-name='due_date' data-url="/users/<%= current_user.id %>/tasks/<%= task.id %>">
      <i><%= task.due_date || Date.today %></i>
    </a>

   <i>priority:</i>

    <a href="#" data-xeditable="true" data-showButtons='false' data-pk="task" data-tpl="<input type='text' style='width: 65px'>" data-model='task' data-name='priority' data-url="/users/<%= current_user.id %>/tasks/<%= task.id %>" data-title="Enter title">
      <%= task.priority %>
    </a>

  </div>
</div>